export const GET_MOVIES_LIST_REQUEST = 'GET_MOVIES_LIST_REQUEST';
export const GET_MOVIES_LIST_SUCCESS = 'GET_MOVIES_LIST_SUCCESS';
export const GET_MOVIES_LIST_FAILURE = 'GET_MOVIES_LIST_FAILURE';
export const CLEAR_MOVIE_LIST = 'CLEAR_MOVIE_LIST';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';